name: Daily-Scheduled-Build

on:
  push:
    branch: 
      - 'spb/add-workflows'

env:
  BUCKET_NAME: 'flow-internal-tooling-bucket'
  DEFAULT_BRANCH: master
  GO_VERSION: '1.17'

jobs:
  tag-version:
    name: Tag and Upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DEFAULT_BRANCH }}

      - name: Get Short Commit
        run: echo "::set-output name=SHORT_COMMIT::daily-$(make short_commit)"
        id: version

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.version.outputs.SHORT_COMMIT }}',
              sha: context.sha
            })

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout Created Tag
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.version.outputs.SHORT_COMMIT }}
        
      - name: Build relic
        run: make crypto_setup_gopath

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_KEY }}

      - name: Docker build
        run: make docker-build-flow

      - name: Docker push
        run: make docker-push-flow

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build tools
        run: |
          make tool-util
          make tool-bootstrap
          make tool-transit
  
      - id: 'upload-util'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          credentials_json: '${{ secrets.GCP_CD_CREDS }}'
          destination: $BUCKET_NAME/daily/${{ steps.version.outputs.SHORT_COMMIT }}/util
          path: './util'

      - id: 'upload-bootstrap'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          credentials_json: '${{ secrets.GCP_CD_CREDS }}'
          destination: $BUCKET_NAME/daily/${{ steps.version.outputs.SHORT_COMMIT }}/bootstrap
          path: './boostrap'

      - id: 'upload-transit'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          credentials_json: '${{ secrets.GCP_CD_CREDS }}'
          destination: ${{ env.BUCKET_NAME }}/daily/${{ steps.version.outputs.SHORT_COMMIT }}/transit
          path: './util'
