name: Sync From Public flow-go Repo

on:
  schedule:
    # run every 12 hours, Mon-Fri
    - cron:  "0 0,12 * * 1-5"
  workflow_dispatch:

# GH_TOKEN needed to enable GitHub CLI commands
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  flow-go-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # checkout entire history - necessary when pushing to multiple origin branches after syncing with public flow-go repo
          fetch-depth: 0

      - name: Run sync
        run: sh sync-from-public-flow-go.sh
