name: Sync From Public flow-go Repo

on:
  schedule:
    # run every 12 hours, Mon-Fri
    - cron:  "0 0,12 * * 1-5"
  workflow_dispatch:
    branches:
      - master-private

# GH_TOKEN needed to enable GitHub CLI commands
env:
  GH_TOKEN: ${{ secrets.REPO_SYNC }}

jobs:
  flow-go-sync:
    runs-on: ubuntu-latest
    permissions:
      actions: write # This is needed to update a workflow file
      contents: write # This is needed to push changes to the repository
      checks: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # checkout entire history - necessary when pushing to multiple origin branches after syncing with public flow-go repo
          fetch-depth: 0

      - name: Run sync
        run: sh tools/repo_sync/sync-from-public-flow-go.sh
