name: Sync From Public flow-go Repo

on:
  schedule:
    # run every 12 hours, Mon-Fri
    - cron:  "0 0,12 * * 1-5"
  workflow_dispatch:
    branches:
      - master-private

# GH_TOKEN needed to enable GitHub CLI commands from scripts
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  flow-go-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # checkout entire history - necessary when pushing to multiple origin branches after syncing with public flow-go repo
          fetch-depth: 0
          token: ${{ secrets.REPO_SYNC }}

      - name: Run sync
        run: sh tools/repo_sync/sync-from-public-flow-go.sh
